spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/devsu
    username: devsu
    password: devsu
client:
  url: ${CLIENT_URL:http://localhost:8080/api/clientes}
server:
  port: 8081
