version: '3.9'
services:
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./BaseDatos.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=devsu
      - POSTGRES_USER=devsu
      - POSTGRES_DB=devsu
    networks:
      - devsu
  client:
    restart: always
    build: ./client/
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - devsu
  account:
    restart: always
    build: ./account/
    depends_on:
      - db
    ports:
      - '8081:8081'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - CLIENT_URL=http://client:8080/api/clientes
    networks:
      - devsu

networks:
  devsu:
    driver: bridge